#!/usr/bin/env python

import sys
import rospy
from turtlesim.srv import Spawn

def spawn_turtle():
    rospy.init_node('spawn_turtle_client')
    rospy.wait_for_service('spawn')
    try:
        spawn = rospy.ServiceProxy('spawn', Spawn)
        # Spawn turtle2 at x=2.0, y=2.0, theta=0.0
        response = spawn(2.0, 2.0, 0.0, 'turtle2')
        print("Successfully spawned: %s" % response.name)
    except rospy.ServiceException as e:
        print("Service call failed: %s" % e)

if __name__ == "__main__":
    spawn_turtle()
